# Generated by Django 3.2.3 on 2021-06-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
