# Generated by Django 3.2.3 on 2021-06-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210620_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='link',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Link'),
        ),
    ]
