# Generated by Django 3.2.4 on 2021-06-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_2',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_3',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='blog',
            name='link',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitle_2',
            field=models.CharField(default=' ', max_length=5000),
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitle_3',
            field=models.CharField(default=' ', max_length=5000),
        ),
    ]
