# Generated by Django 3.2.4 on 2021-06-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210627_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_4',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_5',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_6',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_7',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_8',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_9',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitle_4',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitle_5',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitle_6',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitle_7',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitle_8',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitle_9',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle_2',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle_3',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
