# Generated by Django 3.2.4 on 2021-06-30 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210630_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content_2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content_3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content_4',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content_5',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content_6',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content_7',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content_8',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content_9',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subtitle_2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subtitle_3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subtitle_4',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subtitle_5',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subtitle_6',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subtitle_7',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subtitle_8',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subtitle_9',
        ),
    ]
